### ISSUE TITLE
GEDCOM is not parsed because it is not GEDCOM format 5.5.

### ISSUE THREAD

**Issue by jlnetosci** [jlnetosci/astra#3]
(Since most users of the app are not users of GitHub I will add issues users reported)

`Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/mount/src/astra/app/app.py", line 208, in <module>
    parser = parse_gedcom(uploaded_file)
  File "/mount/src/astra/app/app.py", line 41, in parse_gedcom
    gedcom_parser.parse_file(temp_file_path, False)  # Use the default encoding
  File "/home/adminuser/venv/lib/python3.10/site-packages/gedcom/parser.py", line 145, in parse_file
    last_element = self.__parse_line(line_number, line.decode('utf-8-sig'), last_element, strict)
  File "/home/adminuser/venv/lib/python3.10/site-packages/gedcom/parser.py", line 232, in __parse_line
    raise GedcomFormatViolationError(error_message)
gedcom.parser.GedcomFormatViolationError: Line 48342 of document violates GEDCOM format 5.5
Lines must be no more than one level higher than previous line.
See: https://chronoplexsoftware.com/gedcomvalidator/gedcom/gedcom-5.5.pdf`

**Comment by jlnetosci** [comment]
v0.1.2b tackled this by raising a clearer error message, and guiding toward a solution. v0.2.0b kept the same resolution, but is more opinionated when validating GEDCOM files (checking for duplicate entries, check the file endings, etc.) and automatically corrects (or tosses out, if uncorrectable) impossible situations. v0.2.0b also raises clearer error messages in the edge cases.
